### ISSUE TITLE
OteyPiano crash server on free

### ISSUE THREAD

**Issue by redFrik** [supercollider/sc3-plugins#236]
macOs 10.12.6, sc3.10.0, sc3-plugins-3.10.0

running the first example in OteyPiano helpfile and either x.free or cmd+. and the server crashes.
```supercollider
(
x = {OteyPiano.ar(50,0.5,)}.play;
)
x.free;
```

resulting error...
```
Server 'localhost' exited with exit code 0.
server 'localhost' disconnected shared memory interface
```

same with OteyPianoStrings.

not sure if this related but here a similar issue that was fixed and closed https://github.com/supercollider/sc3-plugins/issues/76

the same example is *not* crashing under sc3.9.3 and sc3-plugins-3.9.1

**Comment by sonoro1234** [comment]
It could be related with #223

**Comment by sonoro1234** [comment]
lets hope that #244 solves it

**Comment by sonoro1234** [comment]
@redFrik Is this solved in last master?

**Comment by redFrik** [comment]
yes, if i build sc3-plugins from current master the problem is gone.
(the problem still exists in sc3-plugins-3.10.0-macOS.zip)
thank you.

**Comment by cdbzb** [comment]
aaarg - experiencing this crash running 3.10.0-macOS.zip - please advise! thanks in advance...

**Comment by VictorKolb** [comment]
` 3.10.0-macOS.zip`
still crashing(

**Comment by sonoro1234** [comment]
> yes, if i build sc3-plugins from current master the problem is gone.
> (the problem still exists in sc3-plugins-3.10.0-macOS.zip)

So it seems that sc3-plugins-3.10.0-macOS.zip should be built from master?

**Comment by joshpar** [comment]
Please try the Mac OS downloads at:
https://github.com/supercollider/sc3-plugins/releases/tag/Version-3.11.0-RC
Windows, etc., coming soon

**Comment by dyfer** [comment]
Works for me!
3.11.0-rc1 signed release
macOS 10.13
